# Generated by Django 2.2.6 on 2021-10-31 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckInv1',
            fields=[
                ('cod_chek_in', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('horario', models.DateField()),
                ('documento', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('cod_check_out', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('horario', models.DateField()),
                ('documento', models.BinaryField()),
                ('multa', models.BigIntegerField(blank=True, null=True)),
                ('multa_1', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('cod_conductor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('run', models.IntegerField()),
                ('nombre', models.CharField(max_length=15)),
                ('apellido_p', models.CharField(max_length=15)),
                ('apellido_m', models.CharField(max_length=15)),
                ('tipo_licencia', models.CharField(max_length=10)),
                ('cod_transporte', models.CharField(max_length=6, unique=True)),
                ('dv', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cod_depa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fotos', models.BinaryField()),
                ('dormitorios', models.CharField(max_length=10)),
                ('banos', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=20)),
                ('valor_depa_xdia', models.BigIntegerField()),
                ('evaluo_inv_total', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cod_invetario', models.CharField(db_column='cod__invetario', max_length=6, unique=True)),
                ('nombre_obj', models.CharField(max_length=50)),
                ('cantidad', models.BigIntegerField()),
                ('estado_obj', models.CharField(max_length=50)),
                ('cod_depa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('evaluo_obj', models.BigIntegerField()),
                ('tipo_objeto', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('cod_depa', models.CharField(max_length=6, unique=True)),
                ('cod_mantenimiento', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('reparacion', models.CharField(max_length=50)),
                ('disponiblidad', models.CharField(max_length=2)),
                ('mejora', models.CharField(max_length=50)),
                ('limpieza', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('pago_parcial', models.BigIntegerField()),
                ('tipo_reserva', models.CharField(max_length=50)),
                ('pago_completo', models.BigIntegerField()),
                ('pago_aprobado', models.BooleanField()),
                ('check_inv2_cod_chek_in', models.ForeignKey(db_column='check_inv2_cod_chek_in', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.CheckInv1')),
                ('check_out_cod_check_out', models.ForeignKey(db_column='check_out_cod_check_out', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.CheckOut')),
                ('departamento_cod_depa', models.ForeignKey(db_column='departamento_cod_depa', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('cod_tour', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('horario', models.DateField()),
                ('fecha', models.DateField()),
                ('tipo_tour', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=50)),
                ('tipo_us', models.BooleanField()),
                ('contrasena', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('cod_vehiculo', models.CharField(max_length=6)),
                ('tipo_vehiculo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('patente', models.CharField(max_length=6)),
                ('cod_transporte', models.CharField(max_length=6, unique=True)),
                ('cod_vehiculo2', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('cod_zona', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('cod_transporte', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=50)),
                ('horario', models.DateField()),
                ('desde', models.CharField(max_length=50)),
                ('hasta', models.CharField(max_length=50)),
                ('conductor_cod_conductor', models.ForeignKey(db_column='conductor_cod_conductor', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.Conductor')),
                ('vehiculo_cod_vehiculo1', models.ForeignKey(db_column='vehiculo_cod_vehiculo1', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('cod_serv', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('reserva_cod_reserva', models.ForeignKey(db_column='reserva_cod_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.Reserva')),
                ('tour_cod_tour', models.ForeignKey(db_column='tour_cod_tour', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.Tour')),
                ('transporte_cod_transporte', models.ForeignKey(db_column='transporte_cod_transporte', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.Transporte')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario_run',
            field=models.ForeignKey(db_column='usuario_run', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.Usuario'),
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.DjangoContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.AuthUser')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='inventario_cod_invetario',
            field=models.ForeignKey(db_column='inventario_cod__invetario', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.Inventario'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='mantenimiento_cod_mantenimiento',
            field=models.ForeignKey(db_column='mantenimiento_cod_mantenimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.Mantenimiento'),
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.AuthPermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.AuthUser')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.AuthGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.AuthUser')),
            ],
        ),
        migrations.AddField(
            model_name='authpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.DjangoContentType'),
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.AuthGroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.AuthPermission')),
            ],
        ),
    ]
