# Generated by Django 3.1.2 on 2021-11-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Conductores'),
        ),
    ]
