# Generated by Django 3.1.2 on 2021-11-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo_core', '0002_conductor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='asd@ad.cl', max_length=254),
        ),
    ]
