# Generated by Django 3.1.2 on 2021-11-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo_core', '0003_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Departamentos'),
        ),
    ]
