# Generated by Django 3.1.2 on 2021-11-02 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo_core', '0004_departamento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='check_inv2_cod_chek_in',
            field=models.ForeignKey(blank=True, db_column='check_inv2_cod_chek_in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Turismo_core.checkinv1'),
        ),
    ]
