# Generated by Django 3.1.2 on 2021-11-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo_core', '0007_auto_20211102_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cod_inventario',
            field=models.CharField(db_column='cod__inventario', max_length=6, unique=True),
        ),
    ]
