# Generated by Django 3.1.2 on 2021-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo_core', '0008_auto_20211102_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cod_depa',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cod_inventario',
            field=models.CharField(db_column='cod__inventario', max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
